main/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from main import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace="users")),
    path('', include('quizzes.urls', namespace="quizzes")),
    path('quizes/', include('quizes.urls', namespace="quizes")),
    path("__debug__/", include("debug_toolbar.urls")),
    path('summernote/', include('django_summernote.urls')),
    re_path(r"^static/(?P<path>.*)$", view=serve)
]
handler404 = 'quizzes.views.Exception404'

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static('/static/', document_root=settings.STATIC_URL)

quizes/urls.py
from django.urls import path

from . import views


app_name = 'quiz'
urlpatterns = [
    path('', views.index, name='index'),

    path('search', views.search, name='search'),
    
    path('<int:quiz_id>/', views.single_quiz, name='single_quiz'),

    path('<int:quiz_id>/<int:question_id>/', views.single_question, name='single_question'),

    path('<int:quiz_id>/results/', views.results, name='results'),

    path('create/', views.create_quiz, name='create_quiz'),

    path('create/<int:quiz_id>/<int:question_id>/', views.create_question, name='create_question'),

    path('edit/<int:quiz_id>/<int:question_id>/', views.edit_question, name='edit_question'),
    
    path('delete/<int:quiz_id>/<int:question_id>/', views.delete_question, name='delete_question'),

    path("material/create", views.create_material, name="create_material"),

    path('material/<int:mat_id>/', views.single_material, name='single_material'),
]

quizzes/urls.py
from django.urls import path, include
from . import views

app_name = 'quizzes'
urlpatterns = [
    path('', views.index, name='index'),
]

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.ulogin, name='login'),

    path('logout/', views.ulogout, name='logout'),

    # path('password-change/', views.UserPasswordChange.as_view(), name="password_change"),

    path('register/', views.register, name='register'),

    path('profile/', views.profile, name='profile'),
    
    path('<int:user_id>/', views.user_page, name='user'),

]

quizzes/models.py
from django.db import models

# No models

quizzes/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponse

def Exception404(request, exception):
    return render(request, "quizzes/404.html")

def index(request):
    return render(request, 'quizzes/index.html')

quizzes/templates/quizzes/base.html
{% load static %}
<!DOCTYPE html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta property="og:type" content="website">
  <meta property="og:title" content="Quizz">
  <meta property="og:description" content="Quizz - место, где рождаются квизы">
  <meta property="og:url" content="{% url 'quizzes:index' %}">
  <meta property="og:image" content="{% static 'favicon.png' %}">
  <meta property="og:site_name" content="Quizz">
  <meta property="og:locale" content="ru_RU">
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon-low.png' %}"/>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous"></title>
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700,700italic|Playfair+Display:400,700&subset=latin,cyrillic">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.css">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
  <script href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js"></script>
  <script href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/popper.js@1.12.6/dist/umd/popper.js" integrity="sha384-fA23ZRQ3G/J53mElWqVJEGJzU0sTs+SvzG8fXVWP+kJQ1lwFAOkcUOysnlKJC33U" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/bootstrap-material-design@4.1.1/dist/js/bootstrap-material-design.js" integrity="sha384-CauSuKpEqAFajSpkdjv3z9t8E7RlpJ1UP0lKM/+NdtSarroVKu069AlsRPKkFBz9" crossorigin="anonymous"></script>
  <style>
    @import url("https://fonts.googleapis.com/css?family=Lobster");
    h1,
    h2,
    h3,
    h4,
    h5,
    h6,
    p,
    span {
        color: white;
        text-decoration: none;
        font-family: "Comic Sans MS"; !important
    }
    html {
        text-decoration: none;
        box-sizing: border-box;
        font-family: "Roboto", helvetica, arial, sans-serif;
        -webkit-touch-callout: none;
        -webkit-user-select: none;
        -khtml-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
    }
    body {
        background-color: #272727;
    }
    li {
        list-style: none;
    }
    label[for="main_menu"],
    nav {
        -moz-transition: all 0.2s cubic-bezier(0.23, 1, 0.32, 1);
        -o-transition: all 0.2s cubic-bezier(0.23, 1, 0.32, 1);
        -webkit-transition: all 0.2s cubic-bezier(0.23, 1, 0.32, 1);
        transition: all 0.2s cubic-bezier(0.23, 1, 0.32, 1);
    }
    .logo {
        margin: 0;
        display: block;
        font-size: 1.5em;
        font-weight: 700;
        font-family: "Lobster", cursive;
        color: #fff;
        padding: 0.5em 1em 0.5em 0.5em;
    }
    nav {
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
    }
    .bg-black {
        background-color: #000;
    }
    #logo {
        width: 30px;
        height: 30px;
        border-radius: 4px;
    }
    .navbar-brand {
        padding: 14px 20px;
        font-size: 16px;
    }
    .navbar-nav {
        width: 100%;
    }
    .nav-item {
        padding: 6px 14px;
        text-align: center;
    }
    .nav-link {
        padding-bottom: 10px;
        font-size: 15px;
        font-weight: 5px;
    }
    .v-line {
        background-color: gray;
        width: 1px;
        height: 20px;
    }
    .navbar-collapse.collapse.in {
        display: block !important;
    }
    @media(max-width: 576px) {
        .nav-item {
            width: 100%;
            text-align: left;
        }
        .v-line {
            display: none;
        }
    }
    .profile-image {
        width: 9%;
        height: 9%;
        aspect-ratio: 1;
        border-color: white;
    }
    .card {
        background-color: #fffaca;
    }
    .form-error {
        color: white;
    }
    .form-icon {
        text-align: center;
        background-color: rgba(255, 255, 255, 0.13);
        border-radius: 50%;
        font-size: 40px;
        color: white;
        width: 100px;
        height: 100px;
        margin: auto auto 50px;
        line-height: 100px;
    }
    img {
        pointer-events: none;
    }
</style>
{% block head %}{% endblock %}
</head>
<body>
<div class="container-fluid px-0">
    <nav class="navbar navbar-expand-sm navbar-dark bg-black py-0 px-0">
        <a class="navbar-brand" href="{% url 'quizzes:index' %}" style="font-family: Vladimir Script; font-size: 25px;">
            <img id="logo" src="{% static 'favicon-low.png' %}">
                &nbsp;&nbsp;&nbsp;Quizz</a>
            <span class="v-line"></span>
            <button class="navbar-toggler mr-3" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav w-100">
                    <li class="nav-item" style="justify-content: center; text-align: center;">
                        <a class="nav-link" style="background-color: black;;color:white; font-family: Comic Sans MS;" href="{% url 'quiz:index' %}">Квизы</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item" style="justify-content: center; text-align: center;">
                            <a class="nav-link" style="background-color: black;;color:white; font-family: Comic Sans MS;" href="{% url 'quiz:create_quiz' %}">Новый квиз</a>
                        </li>
                        <li class="nav-item" style="justify-content: center; text-align: center;">
                            <a class="nav-link" style="background-color: black;;color:white; font-family: Comic Sans MS;" href="{% url 'quiz:create_material' %}">Новый материал</a>
                        </li>
                        <li class="nav-item  ml-auto" style="justify-content: center; text-align: center;">
                            <a class="nav-link" style="background-color: black;;color:white; font-family: Comic Sans MS; justify-content: center;" href="{% url 'users:profile' %}">Профиль</a>
                        </li>
                    {% else %}
                        <li class="nav-item" style="justify-content: center; text-align: center;">
                            <a class="nav-link" style="background-color: black;;color:white; font-family: Comic Sans MS; justify-content: center;" href="{% url 'users:login' %}">Логин</a>
                        </li>
                        <li class="nav-item" style="justify-content: center; text-align: center;">
                            <a class="nav-link" style="background-color: black;;color:white; font-family: Comic Sans MS; justify-content: center;" href="{% url 'users:register' %}">Регистрация</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </div>
    {% block content %}{% endblock content %}
</body>
</html>