main/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from main import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace="users")),
    path('', include('quizzes.urls', namespace="quizzes")),
    path('quizes/', include('quizes.urls', namespace="quizes")),
    path("__debug__/", include("debug_toolbar.urls")),
    path('summernote/', include('django_summernote.urls')),
    re_path(r"^static/(?P<path>.*)$", view=serve)
]
handler404 = 'quizzes.views.Exception404'

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static('/static/', document_root=settings.STATIC_URL)

quizes/urls.py
from django.urls import path

from . import views


app_name = 'quiz'
urlpatterns = [
    path('', views.index, name='index'),

    path('search', views.search, name='search'),
    
    path('<int:quiz_id>/', views.single_quiz, name='single_quiz'),

    path('<int:quiz_id>/<int:question_id>/', views.single_question, name='single_question'),

    path('<int:quiz_id>/results/', views.results, name='results'),

    path('create/', views.create_quiz, name='create_quiz'),

    path('create/<int:quiz_id>/<int:question_id>/', views.create_question, name='create_question'),

    path('edit/<int:quiz_id>/<int:question_id>/', views.edit_question, name='edit_question'),
    
    path('delete/<int:quiz_id>/<int:question_id>/', views.delete_question, name='delete_question'),

    path("material/create", views.create_material, name="create_material"),

    path('material/<int:mat_id>/', views.single_material, name='single_material'),
]

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.ulogin, name='login'),

    path('logout/', views.ulogout, name='logout'),

    # path('password-change/', views.UserPasswordChange.as_view(), name="password_change"),

    path('register/', views.register, name='register'),

    path('profile/', views.profile, name='profile'),
    
    path('<int:user_id>/', views.user_page, name='user'),

]

quizes/models.py
from django.db import models
from jsonfield import JSONField

class Topic(models.Model):
    topic_name = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.topic_name

class Quiz(models.Model):
    quiz_title = models.CharField(max_length=300)
    quiz_description = models.CharField(null=True, blank=True, max_length=3000, verbose_name="quiz_description")
    user_creator = JSONField(max_length=2000, verbose_name="user_creator")
    num_questions = models.IntegerField(default=0, blank=True, null=True)
    material = models.IntegerField(null=True, blank=True)
    topic = models.CharField(max_length=150)

    def __str__(self):
        return self.quiz_title


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, blank=True, null=True)
    question_text = models.CharField(max_length=30000000)
    timeout = models.IntegerField(default=0)
    question_num = models.IntegerField(default=0, blank=True, null=True)

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(blank=False, max_length=500)
    correct_choise = models.BooleanField(default=False)

class Material(models.Model):
    name = models.CharField(blank=False, max_length=300000)
    text = models.CharField(null=True, blank=True, max_length=300000)

    def __str__(self):
        return self.name

quizes/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from .models import Question, Choice, Material, Topic
from django_summernote.widgets import SummernoteWidget

class CreateQuizForm(forms.Form):
    quiz_name = forms.CharField(max_length=50, label="Название", widget=forms.TextInput(attrs={'class': 'form-input form-control item'}))
    quiz_description = forms.CharField(max_length=50, label="Описание (необязательно)", widget=forms.TextInput(attrs={'class': 'form-input form-control item'}))
    material = forms.ModelChoiceField(label="Материалы", queryset=Material.objects.all(), required=False, widget=forms.Select(attrs={'class': 'form-input form-control item'}))
    topic = forms.ModelChoiceField(label="Тема", queryset=Topic.objects.all().order_by("topic_name"), widget=forms.Select(attrs={'class': 'form-input form-control item'}))

class SingleQuestionForm(forms.Form):
    def __init__(self, q_id, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields = {}
        question_id = q_id
        choises = Question.objects.get(id=question_id).choice_set.all()
        for i, choise in enumerate(choises):
            self.fields[f"choise_{i+1}"] = forms.BooleanField(required=False, label=choise.text, widget=forms.CheckboxInput(attrs={'class': 'form-check', "id": f"choise_{i+1}"}))
            self.fields[f"choise_{i+1}"].label = choise.text
    def checkbox_label(self, checkbox):
        return self.fields[checkbox].text

class CreateQuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['timeout', 'question_text']
        widgets = {'question_text': SummernoteWidget(attrs={'class': 'form-control item'}), "name": forms.TextInput(attrs={'class': 'form-input form-control item', 'width': 'auto', 'height': 'auto'})}

class MaterialForm(forms.ModelForm):
    class Meta:
        model = Material
        fields = ['name', 'text']
        widgets = {'text': SummernoteWidget(attrs={'class': 'form-control item'}), "name": forms.TextInput(attrs={'class': 'form-input form-control item', 'width': 'auto', 'height': 'auto', 'min': 0})}

quizes/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.exceptions import MultipleObjectsReturned
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.forms import formset_factory
from django.db.models import Q
import json

from .models import Quiz, Question, Choice, Material, Topic
from .forms import CreateQuizForm, SingleQuestionForm, MaterialForm, CreateQuestionForm
from users.models import User

from django.core.servers.basehttp import WSGIServer
WSGIServer.handle_error = lambda *args, **kwargs: None

def index(request):
    all_quiz_list = Quiz.objects.all()
    context = {
        'all_quiz_list': all_quiz_list,
        'topics': Topic.objects.all(),
    }
    if request.method == "POST":
        data = request.POST.dict()
        quiz_title = data["name"] or ""
        topic = data["topic"] or ""
        url = reverse('quiz:search')+f"?name={quiz_title}&topic={topic}"
        return HttpResponseRedirect(url)
    return render(request, 'quiz/index.html', context)

def search(request):
    if request.method == "GET":
        data = request.GET.dict()
        quiz_title = data["name"] or ""
        topic = data["topic"] or ""
        all_quiz_list = Quiz.objects.filter(Q(quiz_title__contains=quiz_title) & Q(topic__contains=topic))
        context = {
            'all_quiz_list': all_quiz_list,
            'topics': Topic.objects.all(),
        }
    if request.method == "POST":
        data = request.POST.dict()
        quiz_title = data["name"] or ""
        topic = data["topic"] or ""
        url = reverse('quiz:search')+f"?name={quiz_title}&topic={topic}"
        HttpResponseRedirect(reverse('quiz:index'))
        return HttpResponseRedirect(url)
    return render(request, 'quiz/index.html', context)

def topic(request, topic):
    all_quiz_list = Quiz.objects.filter(topic=topic)
    context = {
        'all_quiz_list': all_quiz_list,
        'topics': Topic.objects.all(),
    }
    if request.method == "POST":
        HttpResponseRedirect(reverse('quiz:index'))
        return HttpResponseRedirect(reverse('quiz:search', args=([request.POST.get("search-field"),])))
    return render(request, 'quiz/search.html', context)

def single_quiz(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    num_questions = len(quiz.question_set.all())
    quiz_questions = Question.objects.filter(quiz=quiz)
    materials = quiz.material
    material = None
    if materials:
        material = Material.objects.get(id=materials)
    quiz.num_questions = num_questions
    quiz.save()
    request.session["questions"] = []
    request.session["q_num"] = 1
    request.session["num_correct"] = 0
    request.session["num_wrong"] = 0
    request.session["all_result"] = 0
    request.session["num_partially_true"] = 0
    quiz_question = None
    if quiz_questions.count():
        quiz_question = Question.objects.filter(quiz=quiz)[0]
        if request.POST:
            return HttpResponseRedirect(reverse('quiz:single_question', args=(quiz.id, quiz_question.id,)))
    context = {
        'userId': request.user.id,
        'current_question': quiz_question,
        'quiz': quiz,
        'quiz_questions': quiz_questions,
        'num_questions': num_questions,
        'user_creator': quiz.user_creator,
        'material': material,
        'url': request.build_absolute_uri(),
    }
    return render(request, 'quiz/single_quiz.html', context)

@login_required(login_url="users:login")
def single_question(request, quiz_id, question_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    question = Question.objects.filter(quiz=quiz, id=question_id).first()
    if request.method == "POST":
        form = SingleQuestionForm(data=request.POST, q_id=question_id)
        if not question.id in request.session["questions"]:
            question = Question.objects.filter(quiz=quiz, id=question_id).first()
            choises = Choice.objects.filter(question=question).all()
            correct_choises = Choice.objects.filter(question=question,correct_choise=True).all()
            user_choises = []
            fields = form.fields
            user_result = 0
            if form.is_valid():
                index = 0
                if "continue" in request.POST:
                    user_result = 0
                else:
                    for field in fields:
                        if field[:7] == "choise_":
                            if form.cleaned_data[field] and choises[index].correct_choise:
                                user_result += 1
                            elif form.cleaned_data[field] == False and choises[index].correct_choise == False: pass
                            else:
                                user_result -= 1/choises.count()
                            if form.cleaned_data[field]:
                                user_choises.append(field)
                            index += 1
                    if (not user_choises) and (not correct_choises):
                        user_result += 1
                if user_result > 1:
                    user_result = 1
                    request.session["num_correct"] += 1
                elif user_result < 0:
                    user_result = 0
                    request.session["num_wrong"] += 1
                    print("WRONG")
                else:
                    request.session["num_partially_true"] += 1
                request.session["all_result"] += user_result
                request.session["questions"].append(question.id)
        quiz_questions = list(Question.objects.filter(quiz=quiz))
        q_question_id = quiz_questions.index(Question.objects.get(id=question_id))

        if question != quiz_questions[-1]:
            next_question_id = quiz_questions[q_question_id+1].id
            request.session["q_num"] += 1
            return HttpResponseRedirect(reverse('quiz:single_question', args=(quiz.id, next_question_id,)))
        else:
            return HttpResponseRedirect(reverse('quiz:results', args=(quiz.id,)))
    else:
        form = SingleQuestionForm(q_id=question_id)
    context = {
        'q_num': request.session["q_num"],
        'current_question': question,
        "form": form,
        'quiz': quiz,
    }

    return render(request, 'quiz/single_question.html', context)

@login_required(login_url="users:login")
def results(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)

    num_correct = request.session["num_correct"]
    num_wrong = request.session["num_wrong"]
    num_partially_true = request.session["num_partially_true"]

    total_questions = Question.objects.filter(quiz=quiz).count()
    if num_correct > total_questions:
        num_correct = total_questions
    accuracy = num_correct/(total_questions)

    accuracy_over_75 = False
    if accuracy >= .75:
        accuracy_over_75 = True
    print(request.session["all_result"])
    accuracy_formatted = "{:.0%}".format(request.session["all_result"]/total_questions)

    context = {
        'num_correct': num_correct,
        'num_wrong': num_wrong,
        'num_partially_true': num_partially_true,
        'accuracy_over_75': accuracy_over_75,
        'accuracy_formatted': accuracy_formatted,
        'total_questions': total_questions,
        'quiz': quiz,
    }
    quiz_info = {
        'id': quiz.id,
        'quiz_title': quiz.quiz_title,
        'quiz_description': quiz.quiz_description,
        'topic': quiz.topic,
        'num_correct': str(num_correct),
        'num_wrong': str(num_wrong),
        'num_partially_true': str(num_partially_true),
        'total_questions': str(total_questions),
        'creator': quiz.user_creator
    }
    userModel = User.objects.get(id=request.user.id)
    completed_quizes = eval(str(request.user.completed_quizes))
    completed_quizes.append(quiz_info)
    userModel.completed_quizes = completed_quizes
    userModel.save()
    return render(request, 'quiz/results.html', context)

@login_required(login_url="users:login")
def create_quiz(request):
    if request.method == 'POST':
        form = CreateQuizForm(request.POST)
        if form.is_valid():
            quiz_name = form.cleaned_data['quiz_name']
            quiz_description = form.cleaned_data['quiz_description']
            material = form.cleaned_data['material']
            topic = form.cleaned_data['topic']
            user_info = {
                'id': request.user.id,
                'username': request.user.username,
            }
            new_quiz = Quiz(quiz_title=quiz_name, quiz_description=quiz_description, topic=topic, user_creator=user_info)
            if material:
                new_quiz.material = material.id
            new_quiz.save()
            quiz = Quiz.objects.get(pk=new_quiz.id)
            quiz_info = {
                'id': quiz.id,
                'quiz_title': quiz.quiz_title,
                'quiz_description': quiz.quiz_description,
                'topic': quiz.topic,
                'num_questions': quiz.num_questions or "0"
            }
            userModel = User.objects.get(id=request.user.id)
            created_quizes = eval(request.user.created_quizes)
            created_quizes.append(quiz_info)
            userModel.created_quizes = created_quizes
            userModel.save()
            return HttpResponseRedirect(reverse('quiz:create_question', args=(new_quiz.id, 1,)))
    else:
        form = CreateQuizForm()

    context = {
        'form': form,
    }

    return render(request, 'quiz/create_quiz.html', context)

@login_required(login_url="users:login")
def create_question(request, quiz_id, question_id):
    data = request.POST.dict()
    quiz = Quiz.objects.get(pk=quiz_id)
    if int(quiz.user_creator.get("id")) == int(request.user.id):
        if request.method == 'POST':
            form = CreateQuestionForm(data=request.POST)
            if form.is_valid():

quizes/templates/quiz/create_material.html
{% extends 'quizzes/base.html' %}
{% load static %}
{% block content %}
    <title>Quizz - Создать материал</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/quiz/index.css' %}">
    <div class="container">
    {{form.media}}
    <form method="post">
        <h3 class="question_title">Создать материал</h3>
        {% csrf_token %}
        <label class="choice_label">{{ form.name }}</label>
        <br>
        <div class="col">
        <div class="container">{{ form.text }}</div></div>
        <button type="submit" onclick="this.disabled=true,this.form.submit();">Создать</button>
    </form>
    </div>
{% endblock %}

quizes/templates/quiz/index.html
{% extends 'quizzes/base.html' %}
{% block head %}
    <title>Quizz - Квизы</title>
    <meta charset="UTF-8">
{% endblock %}
{% block content %}
{% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/quiz/index.css' %}">
    <div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0" style="background: #0d1f2a;">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                <form method="post" style="all: initial;">
                    {% csrf_token %}
                    <br>
                    <h3 class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">

                        <span class="fs-5 d-none d-sm-inline" style="font-family: Comic Sans MS; !important">Название</span>
                    </h3>
                    <div class="input-group rounded">
                        <input type="search" name="name" class="form-control rounded" placeholder="Поиск"
                            aria-label="Search" aria-describedby="search-addon" style="font-family: Comic Sans MS; !important" />
                    </div>
                    <br>
                    <h3 class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                        <span class="fs-5 d-none d-sm-inline" style="font-family: Comic Sans MS; !important">Темы</span>
                    </h3>
                    <select style="font-family: Comic Sans MS; !important" class="form-control rounded" name="topic">
                        <option style="font-family: Comic Sans MS; !important" value="{{ topic}}">---</option>
                        {% for topic in topics %}
                        <option style="font-family: Comic Sans MS; !important" value="{{ topic}}">{{ topic }}</option>
                        {% endfor %}
                    </select>
                    <br>
                    <br>
                    <button class="form-control rounded" type="submit"><i class="black fas fa-search" aria-hidden="true" style="color: black;"></i></button>
                </form>
            </div>
        </div>
        <div class="col py-3" style="background: #272727;">
            <div class="container">
                <br>
                {% if all_quiz_list %}
                {% for quiz in all_quiz_list %}
                <br>
                <a class="card" style="text-decoration: none; " href="{% url 'quiz:single_quiz' quiz.id %}">
                    <div class="card-body">
                        <h1 class="card-title" style="font-size: 30px; text-decoration: none !important;">{{ quiz.quiz_title }}</h3>
                            <h4 class="card-subtitle mb-2" style="font-size: 20px;text-decoration: none !important;">Создатель:
                                {{ quiz.user_creator.username }}</h4>
                            <h4 class="card-subtitle mb-2" style="font-size: 15px;text-decoration: none !important;"><i data-v-b2da2d2e=""
                                    data-v-c83df0d5="" class="card-subtitle flex items-center fas fa-list"
                                    style="font-size: 13px;text-decoration: none !important;"></i> Количество вопросов:
                                {{ quiz.num_questions }}</h4>
                            <h4 class="card-subtitle mb-2" style="font-size: 15px;text-decoration: none !important;">Тема: {{ quiz.topic }}</h4>
                    </div>
                </a>
                {% endfor %}
                {% else %}
                <style type="text/css">
                    .container {
                        text-align: center;
                        padding: 5%;
                    }
                </style>
                <p class="h1" style="color: white; font-family: fantasy;">Мы ничего не нашли.</p>
                <img class="img-fluid mx-auto d-block h1" style="height: auto; width: 18%;" src="{% static 'quiz/no_quizes.png' %}">
                {% endif %}
                <br>
                <br>
                <br>
            </div>
        </div>
    </div>
</div>
{% endblock %}

quizes/templates/quiz/no_question.html
<!DOCTYPE html>
<html>
    <head>
        <title>Quizz - Вопрос не найден</title>
    </head>
    <body>
        <h1>Квиз был повреждён. Вопрос не найден</h1>
        <h3>Попробуйте снова или пройдите <a href="{% url 'quizes:index' %}">другие квизы</a></h3>
    </body>
</html>

quizes/templates/quiz/single_quiz.html
{% extends 'quizzes/base.html' %}
{% load static %}
{% block content %}
    <title>Quizz - {{ quiz.quiz_title }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/quiz/index.css' %}">
    <meta charset="UTF-8">
    <title>Single Quiz</title>
    <style>
        .desktop {
            display: block;
        }
        .share, .share:active, .share::after, .share:focus {
          width: auto;
          background-color: transparent;
          border: 1px solid white;
          color: white;
          padding: 10px 20px;
          border-radius: 5%;
          transition: all 0.3s ease;
          text-decoration: none;
        }
        .share:hover {
          background-color: rgba(255, 255, 255, 0.2);
          border: 1px solid white;
          color: white;
          padding: 10px 20px;
          border-radius: 5%;
          transition: all 0.3s ease;
          text-decoration: none;
        }
        .mobile {
            display: none;
        }
        
        @media (max-width: 769px) {
        .desktop {
            display: none;
        }
        .mobile, .mobile:hover, .mobile:focus {
            display: block;
            background-color: transparent;
            border: 1px solid white;
            color: white;
            padding: 10px 20px;
            border-radius: 15%;
            transition: all 0.3s ease;
            text-decoration: none;
        }
        }
      </style>
    <div class="container">
        <form method="post">
            {% csrf_token %}
            <div style="margin-top: 15px; margin-right: 15px;" class="position-absolute top-0 end-0">
                <button type="button" class="btn-link share desktop" onclick="changeIcon(this)">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-share-fill" viewBox="0 0 16 16">
                        <path d="M11 2.5a2.5 2.5 0 1 1 .603 1.628l-6.718 3.12a2.5 2.5 0 0 1 0 1.504l6.718 3.12a2.5 2.5 0 1 1-.488.876l-6.718-3.12a2.5 2.5 0 1 1 0-3.256l6.718-3.12A2.5 2.5 0 0 1 11 2.5"/>
                    </svg>
                    Поделиться
                </button>
                <button type="button" class="btn-link share mobile" onclick="changeIcon(this)">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-share-fill" viewBox="0 0 16 16">
                        <path d="M11 2.5a2.5 2.5 0 1 1 .603 1.628l-6.718 3.12a2.5 2.5 0 0 1 0 1.504l6.718 3.12a2.5 2.5 0 1 1-.488.876l-6.718-3.12a2.5 2.5 0 1 1 0-3.256l6.718-3.12A2.5 2.5 0 0 1 11 2.5"/>
                    </svg>
                </button>
            </div>
            <h3>{{ quiz.quiz_title }}</h3>
            <h4 class="num_questions">Вопросов:
                {{ num_questions }}</h4>
            <h4>Создатель:
                <a style="text-decoration: none;" href="{% url 'users:user' user_creator.id %}">{{ user_creator.username }}</a>
            </h4>
            {% if material %}
                <h4>Дополнительные материалы:
                    <a style="text-decoration: none;" href="{% url 'quiz:single_material' material.id %}">{{ material.name }}
                        ➤</a>
                </h4>
                {% else %}
            {% endif %}
            <button class="btn" type="submit" onclick="this.disabled=true,this.form.submit();">Начать</button>
        </form>
        {% if userId == user_creator.id %}
            <br>
            <a class="btn" href="{% url 'quiz:create_question' quiz.id num_questions|add:1 %}">Добавить вопросы</a>
            <br>
            <br>
            <h3 class="question_title">Вопросы</h3>
            {% for question in quiz_questions %}
                <form style="margin-top: 4%;">
                    <h3 style="color: white; !important">{{ question.question_text | safe }}</h3>
                    {% if question.timeout %}
                    <p>Время: {{ question.timeout }} секунд</p>
                    {% else %}
                    <p>Время: -</p>
                    {% endif %}
                    <a class="item form-group pull-right" href="{% url 'quiz:delete_question' quiz.id question.id %}" onclick="this.disabled=true,this.form.submit();">
                        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 30 30">
                            <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
                        </svg>
                    </a>
                    <a class="item form-group pull-left" href="{% url 'quiz:edit_question' quiz.id question.id %}" onclick="this.disabled=true,this.form.submit();">
                        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 30 30">
                            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                        </svg>
                    </a>
                </form>
            {% endfor %}
            {% else %}
        {% endif %}
    </div>
    <script>
function copyText(text) {
    if (window.clipboardData && window.clipboardData.setData) {
        return window.clipboardData.setData("Text", text);
    }
    else if (document.queryCommandSupported && document.queryCommandSupported("copy")) {
        var textarea = document.createElement("textarea");
        textarea.textContent = text;
        textarea.style.position = "fixed";
        document.body.appendChild(textarea);
        textarea.select();
        try {
            return document.execCommand("copy");
        }
        catch (ex) {
            console.warn("Copy to clipboard failed.", ex);
            return prompt("Copy to clipboard: Ctrl+C, Enter", text);
        }
        finally {
            document.body.removeChild(textarea);
        }
    }
}
        function changeIcon(button) {
  var icon = button.firstElementChild;
  var newIconSVG = '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-all" viewBox="0 0 16 16"> <path d="M8.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L2.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093L8.95 4.992zm-.92 5.14.92.92a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 1 0-1.091-1.028L9.477 9.417l-.485-.486z"/> </svg>';
  
  icon.innerHTML = newIconSVG;
  
  button.disabled = true;
  copyText("{{ url }}");
  setTimeout(function() {
    icon.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-share-fill" viewBox="0 0 16 16"><path d="M11 2.5a2.5 2.5 0 1 1 .603 1.628l-6.718 3.12a2.5 2.5 0 0 1 0 1.504l6.718 3.12a2.5 2.5 0 1 1-.488.876l-6.718-3.12a2.5 2.5 0 1 1 0-3.256l6.718-3.12A2.5 2.5 0 0 1 11 2.5"/></svg>';
    button.disabled = false;
  }, 1000);
}

    </script>
{% endblock %}