main/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from main import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace="users")),
    path('', include('quizzes.urls', namespace="quizzes")),
    path('quizes/', include('quizes.urls', namespace="quizes")),
    path("__debug__/", include("debug_toolbar.urls")),
    path('summernote/', include('django_summernote.urls')),
    re_path(r"^static/(?P<path>.*)$", view=serve)
]
handler404 = 'quizzes.views.Exception404'

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static('/static/', document_root=settings.STATIC_URL)

quizes/urls.py
from django.urls import path

from . import views


app_name = 'quiz'
urlpatterns = [
    path('', views.index, name='index'),

    path('search', views.search, name='search'),
    
    path('<int:quiz_id>/', views.single_quiz, name='single_quiz'),

    path('<int:quiz_id>/<int:question_id>/', views.single_question, name='single_question'),

    path('<int:quiz_id>/results/', views.results, name='results'),

    path('create/', views.create_quiz, name='create_quiz'),

    path('create/<int:quiz_id>/<int:question_id>/', views.create_question, name='create_question'),

    path('edit/<int:quiz_id>/<int:question_id>/', views.edit_question, name='edit_question'),
    
    path('delete/<int:quiz_id>/<int:question_id>/', views.delete_question, name='delete_question'),

    path("material/create", views.create_material, name="create_material"),

    path('material/<int:mat_id>/', views.single_material, name='single_material'),
]

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.ulogin, name='login'),

    path('logout/', views.ulogout, name='logout'),

    # path('password-change/', views.UserPasswordChange.as_view(), name="password_change"),

    path('register/', views.register, name='register'),

    path('profile/', views.profile, name='profile'),
    
    path('<int:user_id>/', views.user_page, name='user'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from jsonfield import JSONField
from uuid import uuid4

class User(AbstractUser):
    photo = models.ImageField(upload_to="users/%Y/%m/%d/", default="users/default.png", blank=True, null=True, verbose_name="Фотография")
    date_birth = models.DateTimeField(blank=True, null=True, verbose_name="Дата рождения")
    completed_quizes = JSONField(null=True, default=[], verbose_name="completed_quizes")
    created_quizes = models.TextField(null=True, default=[], verbose_name="created_quizes")
    email_activated = models.BooleanField(default=False)
    confirm_key = models.TextField(default="")

users/forms.py
from django import forms
from django.contrib.auth.forms import PasswordChangeForm

from .models import User

class LoginUserForm(forms.Form):
    username = forms.CharField(label="Логин",
                    widget=forms.TextInput(attrs={'class': 'form-input form-control item form-control item'}))
    password = forms.CharField(label="Пароль",
                    widget=forms.PasswordInput(attrs={'class': 'form-input form-control item form-control item'}))
    class Meta:
        model = User
        fields = ['username', 'password']

class RegisterForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        labels = {
            'username': 'Логин',
            'email': 'E-mail',
            'password': 'Пароль',
        }
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-input form-control item form-control item'}),
            'email': forms.TextInput(attrs={'class': 'form-input form-control item'}),
            'password': forms.PasswordInput(attrs={'class': 'form-input form-control item form-control item'}),
        }

class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Старый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input form-control item'}))
    new_password1 = forms.CharField(label="Новый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input form-control item'}))
    new_password2 = forms.CharField(label="Подтверждение пароля", widget=forms.PasswordInput(attrs={'class': 'form-input form-control item'}))

users/views.py
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.contrib.auth import login as dj_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeView
from django.template.loader import render_to_string
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.conf import settings

from .forms import LoginUserForm, UserPasswordChangeForm, RegisterForm
from .models import User

from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from uuid import uuid4
import smtplib
from django import template
from django.conf import settings

register = template.Library()

@register.simple_tag
def media(file_path):
    return f"{settings.MEDIA_URL}{file_path}"

def ulogin(request):
    validAuth = ""
    if not request.user.is_authenticated:
        if request.method == "POST":
            form = LoginUserForm(data=request.POST)
            if form.is_valid():
                username = form.cleaned_data["username"]
                password = form.cleaned_data["password"]
                user = User.objects.filter(username=username).first()
                if user and user.check_password(password):
                    dj_login(request, user)
                    return HttpResponseRedirect(reverse('users:profile'))
                else:
                    validAuth = "Неверные логин или пароль"
        else:
            form = LoginUserForm()
        context = {"form": form, "errors": validAuth}
        return render(request, "users/login.html", context=context)
    else:
        return HttpResponseRedirect(reverse('users:profile'))

def register(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            form = RegisterForm(data=request.POST)
            if form.is_valid():
                username = form.cleaned_data["username"]
                email = form.cleaned_data["email"]
                password = form.cleaned_data["password"]
                user = User.objects.create(username=username, email=email, confirm_key=str(uuid4()))
                user.set_password(password)
                user.save()
                context = {"user": user, "url": request.get_host()}
                return HttpResponseRedirect(reverse("users:login"))
        else:
            form = RegisterForm()
        context = {"form": form}
        return render(request, "users/register.html", context=context)
    else:
        return HttpResponseRedirect(reverse('users:profile'))
    
def ulogout(request):
    logout(request)
    return HttpResponseRedirect(reverse('users:login'))


@login_required(login_url="users:login")
def profile(request):
    if request.method == 'POST':
        photo = request.FILES.get('photo')
        if photo:
            request.user.photo = photo
            request.user.save()
    created_quizes = eval(str(request.user.created_quizes))
    context = {'user': request.user, 'created_quizes': created_quizes}
    return render(request, 'users/profile.html', context=context)

def user_page(request, user_id):
    print(user_id)
    user = get_object_or_404(User, id=user_id)
    print(user)
    created_quizes = eval(str(user.created_quizes))
    context = {'user': request.user, "user_page": user, 'created_quizes': created_quizes}
    return render(request, 'users/user.html', context=context)

class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy("users:profile")
    template_name = "users/password_change_form.html"
    # <!-- <a href="{% url 'users:password_change' %}" style="font-family: Comic Sans MS; !important" class="btn btn-dark btn-sm btn-block">Сменить пароль</a> -->

users/templates/users/activate-page.html
{% extends 'quizzes/base.html' %}
{% load static %}
{% block content %}
    <title>Quizz - Логин</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/quiz/index.css' %}">
    <div class="container">
        <form>
            {% if user.email %}
                <h3>Письмо было отправлено на почту: {{ user.email }}</h3>
            {% else %}
                <h3>Неверный код активации</h3>
            {% endif %}
            <h3 style="font-size: 25px;">Проверьте вашу почту и нажмите «Подтвердить», чтобы начать пользоваться нашими функциями</h3>
        </form>
    </div>
{% endblock %}

users/templates/users/activate.html
Подтвердите почту, нажав на ссылку <a href="https://{{ url }}{% url 'users:confirm-email' user.confirm_key %}">Подтвердить</a>

users/templates/users/login.html
{% extends 'quizzes/base.html' %}
{% load static %}
{% block head %}
    <title>Quizz - Логин</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/quiz/index.css' %}">
    <style>
        body {
            background-image: url("{% static 'users/background.jpg' %}");
            background-size: 100% 100%;
        }
    </style>
{% endblock %}
{% block content %}

    <div class="container">
    <div class="registration-form">
        <form method="POST">
            <h3 class="question_title">Логин</h3>
            <br>
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}" />
            <div class="form-icon">
                <span><i class="icon icon-user"></i></span>
            </div>
            <div class="form-error" style="color:white;">{{ form.non_field_errors }}</div>
            {% for f in form %}
                <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
                <div class="form-error" style="color:white;">{{ f.errors }}</div>
            {% endfor %}
            <div style="color: white;">{{ errors }}</div>
            <br>
            <div class="form-group">
                <button type="submit" class="btn btn-block create-account" onclick="this.disabled=true,this.form.submit();">Войти</button>
            </div>
        </form>
    </div>
</div>
        <br>
        <br>
        <br>
{% endblock %}

users/templates/users/password_change_form.html
{% extends 'quizzes/base.html' %}
{% load static %}
{% block content %}
<title>Quizz - Смена пароля</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/quiz/index.css' %}">
        <div class="container">
            <form method="post">
                <h1>Изменение пароля</h1>
                {% csrf_token %}
                <div class="form-error">{{ form.non_field_errors }}</div>
                {% for f in form %}
                    <p>
                        <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}:
                        </label>
                        {{ f }}</p>
                    <div class="form-error">{{ f.errors }}</div>
                {% endfor %}

                <p>
                    <button type="submit">Изменить пароль</button>
                </p>
            </form>
        <br>
        <br>
        <br>
        {% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'users/base.html' %}

{% block content %}
<title>Quizz - Смена пароля</title>
<h1>Пароль изменен</h1>

<p>Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для
  <a href="{% url 'users:login' %}">входа в систему</a>.</p>

{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'users/base.html' %}

{% block content %}
<title>Quizz - Смена пароля</title>
<h1>Новый пароль</h1>

<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p><button type="submit">Сохранить</button></p>
</form>

{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'users/base.html' %}
{% load i18n %}

{% block content %}
<h1>Сброс пароля</h1>

<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'users/base.html' %}

{% block content %}
<title>Quizz - Смена пароля</title>
<h1>Восстановление пароля</h1>

<form method="post">
    {% csrf_token %}
{% for f in form %}
<p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
<div class="form-error">{{ f.errors }}</div>
{% endfor %}

    <p><button type="submit">Сбросить по E-mail</button></p>
</form>

{% endblock %}

users/templates/users/profile.html
{% extends 'quizzes/base.html' %}
{% block content %}
    {% load static %}
    <title>Quizz - Профиль</title>
    <style>
        @import url(https://fonts.googleapis.com/css?family=Lato:400,700,900,300);
        body {
            font-family: "Comic Sans MS"; !important
            background-color: #272727;
            text-decoration: none;
        }
        .container {
            color: whitesmoke;
            font-size: 16px;
            font-family: 'Lato';
        }
        .flex {
            -webkit-box-flex: 1;
            -ms-flex: 1 1 auto;
            flex: 1 1 auto
        }
        .nav-pills .nav-link.active,
        .nav-pills .show > .nav-link {
            background-color: #18293b;
            font-family: "Comic Sans MS"; !important
        }
        .nav-link,
        .nav-link:hover,
        .nav-link:checked {
            background-color: #3f5061;
            color: white;
            font-family: "Comic Sans MS"; !important
        }
        .card {
            color: white;
            text-decoration: none;
            background-color: rgba(255, 255, 255, 0.13);
            justify-content: center;
            border-radius: 10px;
            backdrop-filter: blur(10px);
            border: 2px solid rgba(255, 255, 255, 0.1);
            box-shadow: 0 0 40px rgba(8, 7, 16, 0.6);
            padding: 30px 35px;
        }

        .card:hover{
            color: white;
            transform: scale(1.001);
            box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);
        }
        .profile-container {
    position: relative;
    display: inline-block;
}

.overlay {
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
    background-color: rgba(0, 0, 0, 0.5);
    overflow: hidden;
    width: 100%;
    height: 0;
    transition: .5s ease;
}

.profile-container:hover .overlay {
    height: 30px;
}

.change-password-btn {
    position: absolute;
    bottom: 0;
    left: 50%;
    transform: translateX(-50%);
    z-index: 1;
}

.modal-content {
    background: #343a40;
}
    </style>
    <div class="container" style="padding: 5%;">
        <div class="row py-5 px-4">

            <div class="shadow rounded overflow-hidden" style="background-color: #292929;">
                <div class="px-4 pt-0 pb-4 bg-dark">
                    <div class="media align-items-end profile-header">
                        <div class="profile mr-3">
                            {{ user_page }}
                            <div class="profile-container">
                                <div class="profile" id="profile">
                                    {% if user.photo %}
                                        <img src="{{ user.photo.url }}" alt="User Photo" style="margin-top: 3%;" width="130" class="profile-img" id="profile-img">
                                    {% else %}
                                        <img src="{% static 'users/default.png' %}" alt="..." width="130" class="rounded mb-2 img-thumbnail">
                                    {% endif %}
                                    <div class="overlay" id="overlay">
                                        <a href="{% url 'users:logout' %}" class="btn btn-dark btn-sm btn-block change-password-btn" style="font-family: Comic Sans MS; !important" data-bs-toggle="modal" data-bs-target="#changePhotoModal">
                                        <span class="camera-icon" id="camera-icon"><i class="fas fa-camera"></i></span></a>
                                    </div>
                                </div>
                            </div>
                                <!-- <a href="{% url 'users:logout' %}" style="font-family: Comic Sans MS; !important" class="btn btn-dark btn-sm btn-block" data-bs-toggle="modal" data-bs-target="#changePhotoModal">Сменить пароль</a> -->
                                <a href="{% url 'users:logout' %}" style="font-family: Comic Sans MS; !important" class="btn btn-dark btn-sm btn-block">Выйти</a>
                                <br>
                            </div>
                            <div class="media-body mb-5 text-white">
                                <h4 class="text-break fs-2 font-monospace">{{ user.username }}</h4>
                                {% if user.email %}
                                    <h4 class="text-break font-monospace" style="font-size: 15px;">email:
                                        {{ user.email }}</h4>
                                {% else %}
                                    <h4 class="text-break font-monospace" style="font-size: 15px;">email: -</h4>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="modal fade" id="changePhotoModal" tabindex="-1" aria-labelledby="changePhotoModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="changePhotoModalLabel">Сменить фото</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <form method="post" enctype="multipart/form-data" id="changePhotoForm">
                                        {% csrf_token %}
                                        <input type="file" name="photo" class="form-control mb-3" accept="image/*">
                                        <button type="submit" class="btn btn-primary">Загрузить</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="py-4 px-4">
                        <div class="page-content page-container" id="page-content">
                            <div class="row container d-flex">
                                <div class="col">
                                    <div class="mb-3">
                                        <ul class="nav nav-pills" id="myTab" role="tablist">
                                            <li class="nav-item">
                                                <a class="nav-link active" id="home-tab" data-toggle="tab" href="#created" role="tab" aria-controls="home" aria-selected="true">Созданные квизы</a>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="tab-content">
                                        <div class="tab-pane fade show active" id="created" role="tabpanel" aria-labelledby="home-tab">
                                            <div class="row">
                                                {% if created_quizes %}
                                                    <div class="container mt-4"></div>
                                                    <div class="row g-4">
                                                        {% for quiz in created_quizes %}
                                                            <div class="col md-4">
                                                                <a class="card" style="text-decoration: none; " href="{% url 'quiz:single_quiz' quiz.id %}">
                                                                    <div class="card-body">
                                                                        <h1 class="card-title" style="font-size: 30px; text-decoration: none !important;">{{ quiz.quiz_title }}</h3>
                                                                            <h4 class="card-subtitle mb-2" style="font-size: 15px;text-decoration: none !important;">Тема: {{ quiz.topic }}</h4>
                                                                    </div>
                                                                </a>
                                                            </div>
                                                        {% endfor %}
                                                    </div>
                                                {% else %}
                                                    <p>Нет созданных квизов.</p>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/register_done.html
{% extends 'base.html' %}

{% block content %}
<h1>Добро пожаловать!</h1>

<p>Вы успешно зарегистрировались на сайте! Для входа в систему необходимо авторизоваться по этой
  <a href="{% url 'users:login' %}">ссылке</a>
</p>
{% endblock %}

users/templates/users/user.html
{% extends 'quizzes/base.html' %}
{% block content %}
    {% load static %}
    <title>Quizz - {{ user_page }}</title>
    <style>
        @import url(https://fonts.googleapis.com/css?family=Lato:400,700,900,300);
        body {
            font-family: "Comic Sans MS"; !important
            background-color: #272727;
            text-decoration: none;
        }
        .container {
            color: whitesmoke;
            font-size: 16px;
            font-family: 'Lato';
        }
        .flex {
            -webkit-box-flex: 1;
            -ms-flex: 1 1 auto;
            flex: 1 1 auto
        }
        .nav-pills .nav-link.active,
        .nav-pills .show > .nav-link {
            background-color: #18293b;
            font-family: "Comic Sans MS"; !important
        }
        .nav-link,
        .nav-link:hover,
        .nav-link:checked {
            background-color: #3f5061;
            color: white;
            font-family: "Comic Sans MS"; !important
        }
        .card {
            color: white;
            text-decoration: none;
            background-color: rgba(255, 255, 255, 0.13);
            justify-content: center;
            border-radius: 10px;
            backdrop-filter: blur(10px);
            border: 2px solid rgba(255, 255, 255, 0.1);
            box-shadow: 0 0 40px rgba(8, 7, 16, 0.6);
            padding: 30px 35px;
        }

        .card:hover{
            color: white;
            transform: scale(1.001);
            box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);
        }
        .profile-container {
    position: relative;
    display: inline-block;
}

.overlay {
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
    background-color: rgba(0, 0, 0, 0.5);
    overflow: hidden;
    width: 100%;
    height: 0;
    transition: .5s ease;
}

.profile-container:hover .overlay {
    height: 30px; /* Высота кнопки */
}

.change-password-btn {
    position: absolute;
    bottom: 0;
    left: 50%;
    transform: translateX(-50%);
    z-index: 1;
}

    </style>
    <div class="container" style="padding: 5%;">
        <div class="row py-5 px-4">

            <div class="shadow rounded overflow-hidden" style="background-color: #292929;">
                <div class="px-4 pt-0 pb-4 bg-dark">
                    <div class="media align-items-end profile-header">
                        <div class="profile mr-3">
                            <div class="profile-container">
                                <div class="profile" id="profile">
                                    {% if user_page.photo %}
                                        <img src="{{ user.photo.url }}" alt="User Photo" style="margin-top: 3%;" width="130" class="profile-img" id="profile-img">
                                    {% else %}
                                        <img src="{% static 'users/default.png' %}" alt="..." width="130" class="rounded mb-2 img-thumbnail">
                                    {% endif %}
                                </div>
                            </div>
                                <br>
                                <br>
                                <br>
                            </div>
                            <div class="media-body mb-5 text-white">
                                <h4 class="text-break fs-2 font-monospace">{{ user_page.username }}</h4>
                                {% if user_page.email %}
                                    <h4 class="text-break font-monospace" style="font-size: 15px;">email:
                                        {{ user_page.email }}</h4>
                                {% else %}
                                    <h4 class="text-break font-monospace" style="font-size: 15px;">email: -</h4>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="modal fade" id="changePhotoModal" tabindex="-1" aria-labelledby="changePhotoModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="changePhotoModalLabel">Сменить фото</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <form method="post" enctype="multipart/form-data" id="changePhotoForm">
                                        {% csrf_token %}
                                        <input type="file" name="photo" class="form-control mb-3" accept="image/*">
                                        <button type="submit" class="btn btn-primary">Загрузить</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="py-4 px-4">
                        <div class="page-content page-container" id="page-content">
                            <div class="row container d-flex">
                                <div class="col">
                                    <div class="mb-3">
                                        <ul class="nav nav-pills" id="myTab" role="tablist">
                                            <li class="nav-item">
                                                <a class="nav-link active" id="home-tab" data-toggle="tab" href="#created" role="tab" aria-controls="home" aria-selected="true">Созданные квизы</a>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="tab-content">
                                        <div class="tab-pane fade show active" id="created" role="tabpanel" aria-labelledby="home-tab">
                                            <div class="row">
                                                {% if created_quizes %}
                                                    <div class="container mt-4"></div>
                                                    <div class="row g-4">
                                                        {% for quiz in created_quizes %}
                                                            <div class="col md-4">
                                                                <a class="card" style="text-decoration: none; " href="{% url 'quiz:single_quiz' quiz.id %}">
                                                                    <div class="card-body">
                                                                        <h1 class="card-title" style="font-size: 30px; text-decoration: none !important;">{{ quiz.quiz_title }}</h3>
                                                                            <h4 class="card-subtitle mb-2" style="font-size: 15px;text-decoration: none !important;">Тема: {{ quiz.topic }}</h4>
                                                                    </div>
                                                                </a>
                                                            </div>
                                                        {% endfor %}
                                                    </div>
                                                {% else %}
                                                    <p>Нет созданных квизов.</p>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}